version: "3.9"
services:
  web:
    build: .
    ports:
      - "5005:80"
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"